apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: net-pigeon-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: net-pigeon-go 
  name: net-pigeon-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: net-pigeon-go 
